"""Added image_url to RedFlag and Intervention

Revision ID: 258606514792
Revises: c56c932c98bb
Create Date: 2025-02-24 21:30:01.759716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258606514792'
down_revision = 'c56c932c98bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
