"""Added video_url column to Report model

Revision ID: c4440a14c27a
Revises: 383de3d0f5a8
Create Date: 2025-03-05 09:58:15.433115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4440a14c27a'
down_revision = '383de3d0f5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
