"""Increase image_url column size

Revision ID: 088570b7f127
Revises: c4b0ca2f4aef
Create Date: 2025-03-11 09:36:14.138135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088570b7f127'
down_revision = 'c4b0ca2f4aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=8000),
               existing_nullable=True)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=8000),
               existing_nullable=False)

    with op.batch_alter_table('redflags', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=8000),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('redflags', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=8000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=sa.String(length=8000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=8000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
