"""Changes

Revision ID: 5102daf303af
Revises: 8c84a888cbe5
Create Date: 2025-03-16 11:54:49.855462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5102daf303af'
down_revision = '8c84a888cbe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=19), nullable=True))

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=19), nullable=True))

    # ### end Alembic commands ###
