"""Add image_url

Revision ID: c4b0ca2f4aef
Revises: 2caca08f6c53
Create Date: 2025-03-10 13:14:09.989452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b0ca2f4aef'
down_revision = '2caca08f6c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    with op.batch_alter_table('redflags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redflags', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
