"""Changes

Revision ID: e749fed811d7
Revises: 5102daf303af
Create Date: 2025-03-16 11:56:41.736165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e749fed811d7'
down_revision = '5102daf303af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
